name: ci-job

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'

env:
  DBT_PROFILE_TARGET: dev
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch to runner
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: install python dependancies
        run: pip install -r requirements.txt 

      - name: install dbt dependencies
        run: dbt deps

      - name: dbt test --profiles-dir ./
        run: dbt test

# add task for building changed models + downstream
# configure target to dev